service: zunda-fairy-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: prd
  region: ap-northeast-1
  environment:
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_USER_TOKEN: ${env:SLACK_USER_TOKEN}
    SLACK_BOT_USER: ${env:SLACK_BOT_USER}

functions:
  reply_nanoda:
    handler: src/handler.reply_nanoda
    events:
      - httpApi:
          path: /zunda-fairy/reply
          method: get
  register_nanoda:
    handler: src/handler.register_nanoda
    events:
      - httpApi:
          path: /zunda-fairy/register
          method: get
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
