service: zunda-fairy-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: prd
  region: ap-northeast-1
  environment:
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_USER_TOKEN: ${env:SLACK_USER_TOKEN}
    SLACK_BOT_USER: ${env:SLACK_BOT_USER}

functions:
  handler:
    handler: src/handler.handler
    timeout: 29
    events:
      - httpApi:
          path: /
          method: post
plugins:
  - serverless-python-requirements
  - serverless-offline
custom:
  pythonRequirements:
    dockerizePip: non-linux
